-- AlterTable
ALTER TABLE `messages` ADD COLUMN `metadata` JSON NULL,
    MODIFY `contentType` ENUM('TEXT', 'IMAGE', 'DOCUMENT', 'AUDIO', 'VIDEO', 'LOCATION', 'TEMPLATE', 'INTERACTIVE', 'STICKER', 'CONTACT') NOT NULL DEFAULT 'TEXT';
